spring:
  datasource:
    url: ${HB_DB_URL}
    username: ${HB_DB_USERNAME}
    password: ${HB_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.jdbc.batch_size: 50
  liquibase:
    change-log: classpath:config/liquibase_ext/master.xml
    url: ${HB_DB_URL}
    user: ${HB_DB_USERNAME}
    password: ${HB_DB_PASSWORD}
  cloud:
    consul:
      ribbon:
        enabled: true
      discovery:
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        health-check-interval: 10s
        health-check-timeout: 120s
        prefer-ip-address: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${HB_UAA_URL:http://127.0.0.1:8280}/oauth2/jwks

server:
  port: 8083

feign:
  circuitbreaker:
    enabled: true
    group:
      enabled: true
  client:
    config:
      default:
        loggerLevel: full

application:
  cors:
    allowed-origin: ${HB_ALLOWED_ORIGIN}
  rabbit-mq:
    host: ${HB_RABBIT_MQ_HOST}
    port: ${HB_RABBIT_MQ_PORT}
    username: ${HB_RABBIT_MQ_USERNAME}
    password: ${HB_RABBIT_MQ_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: info,health,httptrace