spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: hb-gateway
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        health-check-interval: 10s
        health-check-timeout: 120s
        prefer-ip-address: true
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
            - Proxy-Authenticate
            - Proxy-Authorization
            - Keep-Alive
            - TE
            - Trailer
            - Transfer-Encoding
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: http://127.0.0.1:3000
#            allowedMethods: GET,PUT,POST,DELETE,OPTIONS,PATCH
#            allowedHeaders: x-requested-with,authorization,Content-Type,Content-Length,Authorization,credential,X-XSRF-TOKEN
#            allowCredentials: true
#            maxAge: 7200
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hb-uaa-route
          uri: http://127.0.0.1:8280
          predicates:
            - Path=/hb-uaa/**
          filters:
            - RewritePath=/hb-uaa/(?<path>.*), /$\{path}
        - id: hb-dmm-route
          uri: lb://hb-dmm
          predicates:
            - Path=/hb-dmm/**
          filters:
            - RewritePath=/hb-dmm/(?<path>.*), /$\{path}
        - id: hb-payment-route
          uri: lb://hb-payment
          predicates:
            - Path=/hb-payment/**
          filters:
            - RewritePath=/hb-payment/(?<path>.*), /$\{path}
#            - name: Retry
#              args:
#                retries: 4
#                series:
#                  - SERVER_ERROR
#                  - CLIENT_ERROR
#                statuses:
#                  - OK
#                methods:
#                  - GET
#                  - POST
#                exceptions:
#                  - java.io.IOException
        - id: hb-notification-route
          uri: lb://hb-notification
          predicates:
            - Path=/hb-notification/**
          filters:
            - RewritePath=/hb-notification/(?<path>.*), /$\{path}path
        - id: hb-notification-ws-route
          uri: lb:ws://hb-notification
          predicates:
            - Path=/hb-notification/**
          filters:
            - RewritePath=/hb-notification/(?<path>.*), /$\{path}path
      httpclient:
        connect-timeout: 5000
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - SetHeaderByCookieFilter
        - TokenRelay=
        - Retry=
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:8280/oauth2/jwks
      client:
        registration:
          hb-gateway:
            provider: hb-uaa
            client-id: hb_client_id_1
            client-secret: hb_client_secret_1
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/hb-gateway
            scope: openid
            client-name: hb-gateway
        provider:
          hb-uaa:
            authorization-uri: http://127.0.0.1:8280/oauth2/authorize
            issuer-uri: http://127.0.0.1:8280
            token-uri: http://127.0.0.1:8280/oauth2/token
            jwk-set-uri: http://127.0.0.1:8280/oauth2/jwks
            user-info-uri: http://127.0.0.1:8280/api/v1/profiles
            user-name-attribute: sub
application:
  uri:
    front-end-user: ${FE_URL:http://127.0.0.1:3000}
logging:
  level:
    root: INFO
    com.netflix: DEBUG